language: java
jdk:
  - oraclejdk6
  - oraclejdk7
  - oraclejdk8
script: mvn clean install
after_success:
- mvn clean cobertura:cobertura coveralls:report
- mvn clean test jacoco:report coveralls:report
